### ISSUE TITLE
sci-mathematics/rsltc fetch failed

### ISSUE THREAD

**Issue by tharvik** [buzden/buzden-overlay#3]
`http://www.iist.unu.edu/newrh/III/3/1/docs/rsltc/linux/rsltc.gz` is not a valid hostname (anymore).

https://github.com/dtu-railway-verification/rsltc seems to replace it, I've a draft ebuild for it, but it depends on [gentle](http://gentle.compilertools.net/) which isn't available either in gentoo tree or on https://gpo.zugaina.org.

So, is `sci-mathematics/rsltc` used or should it be remove from the overlay?

**Comment by buzden** [comment]
As far as I know, those who were using it stopped doing it some years ago. So, it is okay for this ebuild to be removed.

**Comment by buzden** [comment]
This ebuild has been removed in the commit https://github.com/buzden/buzden-overlay/commit/305e3371b63a337dee28df9db064cfac26bb6aad
